### ISSUE TITLE
https://github.com/PennyDreadfulMTG/perf-reports/issues/new

### ISSUE THREAD

**Issue by leonardsmith** [PennyDreadfulMTG/perf-reports#37859]
SELECT 40, bq.id, 'Legal'
    FROM (
    SELECT
        `u`.`id` AS `id`, 
    CASE
    WHEN layout = 'double-faced' OR layout = 'flip' THEN
        GROUP_CONCAT(CASE WHEN `u`.position = 1 THEN face_name ELSE '' END SEPARATOR '')
    WHEN layout = 'meld' THEN
        GROUP_CONCAT(CASE WHEN `u`.position = 1 OR `u`.position = 2 THEN face_name ELSE '' END SEPARATOR '')
    ELSE
        GROUP_CONCAT(face_name SEPARATOR ' // ' )
    END
 AS name, GROUP_CONCAT(`u`.`mana_cost` SEPARATOR '|') AS `mana_cost`, 
    CASE
    WHEN layout = 'split' OR layout = 'aftermath' THEN
        SUM(`u`.cmc)
    WHEN layout = 'meld' THEN
        SUM(CASE WHEN `u`.position = 1 OR `u`.position = 2 THEN cmc ELSE 0 END)
    ELSE
        SUM(CASE WHEN `u`.position = 1 THEN `u`.cmc ELSE 0 END)
    END
 AS cmc, GROUP_CONCAT(CASE WHEN `u`.position = 1 THEN `u`.`power` ELSE '' END SEPARATOR '') AS `power`, GROUP_CONCAT(CASE WHEN `u`.position = 1 THEN `u`.`toughness` ELSE '' END SEPARATOR '') AS `toughness`, GROUP_CONCAT(CASE WHEN `u`.position = 1 THEN `u`.`loyalty` ELSE '' END SEPARATOR '') AS `loyalty`, 
    CASE
    WHEN layout = 'meld' THEN
        GROUP_CONCAT(CASE WHEN `u`.position = 1 OR `u`.position = 2 THEN type ELSE '' END SEPARATOR '')
    ELSE
        GROUP_CONCAT(CASE WHEN `u`.position = 1 THEN type ELSE '' END SEPARATOR '')
    END
 AS type, GROUP_CONCAT(`u`.`text` SEPARATOR '

**Comment by bakert** [comment]
hey @leonardsmith what's the context here?
